export interface AgentDetail {
  id:number;
    name:string;
    role:string
    officeNumber:string;
    mobileNumber:string;
    email:string;
    twitterLink:string;
    linkedinLink:string;
    instagramLink:string;
    youtubeLink:string;
    description:string;
    advertId:number;
    price:number;
    city:string;
    location:string;
    categoryName:string;
    images:string[]
    title:string;
    agentId:number;
}
